CSU08 da Loja completo
edu15076/TCC_Sistema_Loja_SaaS pull request #32
Opened 2024-12-02 20:20 UTC by El0y-C0SM0

Este pull request implementa as funcionalidades relacionadas ao gerenciamento de produtos odertados (CSU08 da loja), incluindo edição de preços, criação de promoções e geração de relatórios detalhados.  

---

## Funcionalidades Completadas  

### 1. **Listagem de Produtos**
- Criada uma interface para exibir todos produtos de uma loja e de uma promoção com as seguintes informações:  
  - Nome do produto.  
  - Preço atual de venda.  
  - Disponibilidade de venda
- Através das interfaces é possivel editar
  -  Preço de venda
  - Se está em venda
  - Quais promoções tem

### 2. **Listagem de Promoções**
- Criadas interfaces para exibir todas as promoções de uma loja e de um produto com as seguintes informações:
  - Descrição
  - Porcentagem de desconto
  - Data de inicio
  - Duração 
- As interfaces também permitem:
  - Duplicar uma promoção
  - Cadastrar uma nova promoção

## Melhorias 

### 1. Melhorias no Controle de Acesso:

-  [`[src/common/templates/acesso_nao_autorizado.html](diffhunk://#diff-39ae3d3b840744488945d4a9c309b6a537727f7cca5d460cf0bfd3cca0d4d9c8R1-R11)`](diffhunk://#diff-39ae3d3b840744488945d4a9c309b6a537727f7cca5d460cf0bfd3cca0d4d9c8R1-R11): Adicionado um novo template para a página de acesso não autorizado.  

### 2. Adição de bibliotecas de imagens
- Adição da biblioteca de imagens [heroicon](https://heroicons.com/) para usar imagens svg no projeto.

### 3. Alertas
- Criação de templates para alertas visuais de erros e avisos em [util/templates/alerts](/src/util/templates/alerts)

### 4. Model Choices customizados
- Implementação de models choices que retornam o objeto, ao invés da label, para viabilizar melhor estilização

## Testes

- Testes para validar acesso e interações com a gestão de oferta dos produtos
- Testes para validar acesso e interações com a gestão das promoções
- Teste para os models de Produto, Promoção e ProdutoPorLote

### Todos

Puequenas tarefas a serem completas futuramente nessa branch mas que não impedem a completude do csu:

- [ ] Refatorar forms da loja para usar LojaValidatorFormMixin e ModelFields
- [ ] Adicionar nav-item's de produtos e promoções para o gerente financeiro
- [ ] Refatorar algumas views para usar get_form_kwargs
- [ ] Adicionar paginação
- [ ] Corrigir pesquisa por produto e adicionar aos forms com model choices
- [ ] Adiconar visualização da quantidade de produtos em estoque

2024-12-02 20:34 UTC, edu15076 commented on src/loja/models/produto.py
Trocar RESTRICT para CASCADE com loja

2024-12-02 20:51 UTC, edu15076 requested changes
Remova o RESTRICT nas relações com loja para que seja viabilizada a deleção da loja

2024-12-03 03:35 UTC, El0y-C0SM0 commented on src/loja/models/produto.py
Resolvido

2024-12-03 03:44 UTC, El0y-C0SM0 commented
> Remova o RESTRITO nas relações com loja para que queda uma viabiliza uma deleção da loja

Feito

2024-12-04 01:01 UTC, edu15076 approved these changes
Aprovado

2024-12-04 01:01 UTC, merged